//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "https://localhost:7174/";
    }

    /**
     * @return OK
     */
    all(): Promise<void> {
        let url_ = this.baseUrl + "/api/ArticleBlog/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAll(_response);
        });
    }

    protected processAll(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    articleBlog(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/ArticleBlog/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processArticleBlog(_response);
        });
    }

    protected processArticleBlog(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getTournamentById(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/GameBlog/get-tournament-by-id/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetTournamentById(_response);
        });
    }

    protected processGetTournamentById(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    details(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/GameBlog/details/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDetails(_response);
        });
    }

    protected processDetails(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    byId(playerId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/PlayerBlog/by-id/{playerId}";
        if (playerId === undefined || playerId === null)
            throw new globalThis.Error("The parameter 'playerId' must be defined.");
        url_ = url_.replace("{playerId}", encodeURIComponent("" + playerId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processById(_response);
        });
    }

    protected processById(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    gameByTournament(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamBlog/game-by-tournament/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGameByTournament(_response);
        });
    }

    protected processGameByTournament(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number, tournamentId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamBlog/get-by-id/{id}/{tournamentId}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (tournamentId === undefined || tournamentId === null)
            throw new globalThis.Error("The parameter 'tournamentId' must be defined.");
        url_ = url_.replace("{tournamentId}", encodeURIComponent("" + tournamentId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param email (optional) 
     * @return OK
     */
    singleemail(email: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Email/singleemail?";
        if (email === null)
            throw new globalThis.Error("The parameter 'email' cannot be null.");
        else if (email !== undefined)
            url_ += "email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSingleemail(_response);
        });
    }

    protected processSingleemail(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    send(body: EmailTemplateDto): Promise<void> {
        let url_ = this.baseUrl + "/api/Email/send";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSend(_response);
        });
    }

    protected processSend(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getTournamentByIdAll(id: number): Promise<GameListDto[]> {
        let url_ = this.baseUrl + "/api/Game/get-tournament-by-id/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetTournamentByIdAll(_response);
        });
    }

    protected processGetTournamentByIdAll(response: Response): Promise<GameListDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GameListDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameListDto[]>(null as any);
    }

    /**
     * @return OK
     */
    details2(id: number): Promise<GameDetailsDto> {
        let url_ = this.baseUrl + "/api/Game/details/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDetails2(_response);
        });
    }

    protected processDetails2(response: Response): Promise<GameDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GameDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    createRoom(body: NewRoomDto): Promise<RoomDTO> {
        let url_ = this.baseUrl + "/api/Room/create-room";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateRoom(_response);
        });
    }

    protected processCreateRoom(response: Response): Promise<RoomDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RoomDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RoomDTO>(null as any);
    }

    /**
     * @return OK
     */
    roomAll(): Promise<RoomDTO[]> {
        let url_ = this.baseUrl + "/api/Room";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRoomAll(_response);
        });
    }

    protected processRoomAll(response: Response): Promise<RoomDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RoomDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RoomDTO[]>(null as any);
    }

    /**
     * @return OK
     */
    room(id: number): Promise<RoomDTO> {
        let url_ = this.baseUrl + "/api/Room/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRoom(_response);
        });
    }

    protected processRoom(response: Response): Promise<RoomDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RoomDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RoomDTO>(null as any);
    }

    /**
     * @return OK
     */
    my(): Promise<RoomDTO[]> {
        let url_ = this.baseUrl + "/api/Room/my";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMy(_response);
        });
    }

    protected processMy(response: Response): Promise<RoomDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RoomDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RoomDTO[]>(null as any);
    }

    /**
     * @return OK
     */
    join(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Room/{id}/join";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processJoin(_response);
        });
    }

    protected processJoin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    leave(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Room/{id}/leave";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLeave(_response);
        });
    }

    protected processLeave(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param roomId (optional) 
     * @return OK
     */
    allAll(roomId: number | undefined): Promise<RoomGameDto[]> {
        let url_ = this.baseUrl + "/api/RoomGame/all?";
        if (roomId === null)
            throw new globalThis.Error("The parameter 'roomId' cannot be null.");
        else if (roomId !== undefined)
            url_ += "roomId=" + encodeURIComponent("" + roomId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAllAll(_response);
        });
    }

    protected processAllAll(response: Response): Promise<RoomGameDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RoomGameDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RoomGameDto[]>(null as any);
    }

    /**
     * @param roomId (optional) 
     * @param gameId (optional) 
     * @return OK
     */
    other(roomId: number | undefined, gameId: number | undefined): Promise<OtherGameBetSimpleDto[]> {
        let url_ = this.baseUrl + "/api/RoomGame/other?";
        if (roomId === null)
            throw new globalThis.Error("The parameter 'roomId' cannot be null.");
        else if (roomId !== undefined)
            url_ += "roomId=" + encodeURIComponent("" + roomId) + "&";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "gameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOther(_response);
        });
    }

    protected processOther(response: Response): Promise<OtherGameBetSimpleDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(OtherGameBetSimpleDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OtherGameBetSimpleDto[]>(null as any);
    }

    /**
     * @return OK
     */
    roomGame(body: RoomGameBetDto): Promise<void> {
        let url_ = this.baseUrl + "/api/RoomGame";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRoomGame(_response);
        });
    }

    protected processRoomGame(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param gameid (optional) 
     * @return OK
     */
    usersInRoom(gameid: number | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/RoomInside/UsersInRoom?";
        if (gameid === null)
            throw new globalThis.Error("The parameter 'gameid' cannot be null.");
        else if (gameid !== undefined)
            url_ += "gameid=" + encodeURIComponent("" + gameid) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUsersInRoom(_response);
        });
    }

    protected processUsersInRoom(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param emial (optional) 
     * @return OK
     */
    sentInvitationEmail(gameid: number, emial: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/RoomInside/{gameid}/sent-invitation-email?";
        if (gameid === undefined || gameid === null)
            throw new globalThis.Error("The parameter 'gameid' must be defined.");
        url_ = url_.replace("{gameid}", encodeURIComponent("" + gameid));
        if (emial === null)
            throw new globalThis.Error("The parameter 'emial' cannot be null.");
        else if (emial !== undefined)
            url_ += "emial=" + encodeURIComponent("" + emial) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSentInvitationEmail(_response);
        });
    }

    protected processSentInvitationEmail(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    scheduler(): Promise<void> {
        let url_ = this.baseUrl + "/api/Scheduler";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processScheduler(_response);
        });
    }

    protected processScheduler(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    tournament(): Promise<TournamentDto[]> {
        let url_ = this.baseUrl + "/api/Tournament";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTournament(_response);
        });
    }

    protected processTournament(response: Response): Promise<TournamentDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TournamentDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TournamentDto[]>(null as any);
    }

    /**
     * @return OK
     */
    register(body: RegistrationReq): Promise<void> {
        let url_ = this.baseUrl + "/api/User/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    login(body: LoginReq): Promise<string> {
        let url_ = this.baseUrl + "/api/User/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    getCurrentUser(): Promise<UserDto> {
        let url_ = this.baseUrl + "/api/User/GetCurrentUser";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCurrentUser(_response);
        });
    }

    protected processGetCurrentUser(response: Response): Promise<UserDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDto>(null as any);
    }

    /**
     * @return OK
     */
    groupBlog(): Promise<void> {
        let url_ = this.baseUrl + "/api/GroupBlog";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGroupBlog(_response);
        });
    }

    protected processGroupBlog(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class EmailTemplateDto implements IEmailTemplateDto {
    toAddress!: string;
    templateId?: number;
    userId?: number;

    [key: string]: any;

    constructor(data?: IEmailTemplateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.toAddress = _data["toAddress"];
            this.templateId = _data["templateId"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): EmailTemplateDto {
        data = typeof data === 'object' ? data : {};
        let result = new EmailTemplateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["toAddress"] = this.toAddress;
        data["templateId"] = this.templateId;
        data["userId"] = this.userId;
        return data;
    }
}

export interface IEmailTemplateDto {
    toAddress: string;
    templateId?: number;
    userId?: number;

    [key: string]: any;
}

export class GameDetailsDto implements IGameDetailsDto {
    id?: number;
    startTime?: Date;
    teams!: GameDetailsTeamDto[];
    finalScore?: string | undefined;
    tournamentId?: number;
    referee?: string | undefined;
    headToHead!: HeadToHeadDto[];

    [key: string]: any;

    constructor(data?: IGameDetailsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.teams = [];
            this.headToHead = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : undefined as any;
            if (Array.isArray(_data["teams"])) {
                this.teams = [] as any;
                for (let item of _data["teams"])
                    this.teams!.push(GameDetailsTeamDto.fromJS(item));
            }
            this.finalScore = _data["finalScore"];
            this.tournamentId = _data["tournamentId"];
            this.referee = _data["referee"];
            if (Array.isArray(_data["headToHead"])) {
                this.headToHead = [] as any;
                for (let item of _data["headToHead"])
                    this.headToHead!.push(HeadToHeadDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GameDetailsDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameDetailsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : undefined as any;
        if (Array.isArray(this.teams)) {
            data["teams"] = [];
            for (let item of this.teams)
                data["teams"].push(item ? item.toJSON() : undefined as any);
        }
        data["finalScore"] = this.finalScore;
        data["tournamentId"] = this.tournamentId;
        data["referee"] = this.referee;
        if (Array.isArray(this.headToHead)) {
            data["headToHead"] = [];
            for (let item of this.headToHead)
                data["headToHead"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IGameDetailsDto {
    id?: number;
    startTime?: Date;
    teams: GameDetailsTeamDto[];
    finalScore?: string | undefined;
    tournamentId?: number;
    referee?: string | undefined;
    headToHead: HeadToHeadDto[];

    [key: string]: any;
}

export class GameDetailsTeamDto implements IGameDetailsTeamDto {
    id?: number;
    name?: string;
    logoUrl!: string;
    tactic?: string | undefined;
    players!: PlayerBasicInfoDto[];
    coach!: string;
    formLastGames!: string;

    [key: string]: any;

    constructor(data?: IGameDetailsTeamDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.players = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.logoUrl = _data["logoUrl"];
            this.tactic = _data["tactic"];
            if (Array.isArray(_data["players"])) {
                this.players = [] as any;
                for (let item of _data["players"])
                    this.players!.push(PlayerBasicInfoDto.fromJS(item));
            }
            this.coach = _data["coach"];
            this.formLastGames = _data["formLastGames"];
        }
    }

    static fromJS(data: any): GameDetailsTeamDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameDetailsTeamDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["logoUrl"] = this.logoUrl;
        data["tactic"] = this.tactic;
        if (Array.isArray(this.players)) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item ? item.toJSON() : undefined as any);
        }
        data["coach"] = this.coach;
        data["formLastGames"] = this.formLastGames;
        return data;
    }
}

export interface IGameDetailsTeamDto {
    id?: number;
    name?: string;
    logoUrl: string;
    tactic?: string | undefined;
    players: PlayerBasicInfoDto[];
    coach: string;
    formLastGames: string;

    [key: string]: any;
}

export class GameListDto implements IGameListDto {
    id?: number;
    startTime?: Date;
    teams!: GameListTeamDto[];
    finalScore?: string | undefined;

    [key: string]: any;

    constructor(data?: IGameListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.teams = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : undefined as any;
            if (Array.isArray(_data["teams"])) {
                this.teams = [] as any;
                for (let item of _data["teams"])
                    this.teams!.push(GameListTeamDto.fromJS(item));
            }
            this.finalScore = _data["finalScore"];
        }
    }

    static fromJS(data: any): GameListDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : undefined as any;
        if (Array.isArray(this.teams)) {
            data["teams"] = [];
            for (let item of this.teams)
                data["teams"].push(item ? item.toJSON() : undefined as any);
        }
        data["finalScore"] = this.finalScore;
        return data;
    }
}

export interface IGameListDto {
    id?: number;
    startTime?: Date;
    teams: GameListTeamDto[];
    finalScore?: string | undefined;

    [key: string]: any;
}

export class GameListTeamDto implements IGameListTeamDto {
    id?: number;
    name!: string;
    logoUrl!: string;

    [key: string]: any;

    constructor(data?: IGameListTeamDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.logoUrl = _data["logoUrl"];
        }
    }

    static fromJS(data: any): GameListTeamDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameListTeamDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["logoUrl"] = this.logoUrl;
        return data;
    }
}

export interface IGameListTeamDto {
    id?: number;
    name: string;
    logoUrl: string;

    [key: string]: any;
}

export class HeadToHeadDto implements IHeadToHeadDto {
    gameId?: number;
    gameDate?: Date;
    finalScore!: string;
    teamId1?: number;
    teamId2?: number;
    teamName1!: string;
    teamName2!: string;

    [key: string]: any;

    constructor(data?: IHeadToHeadDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.gameId = _data["gameId"];
            this.gameDate = _data["gameDate"] ? new Date(_data["gameDate"].toString()) : undefined as any;
            this.finalScore = _data["finalScore"];
            this.teamId1 = _data["teamId1"];
            this.teamId2 = _data["teamId2"];
            this.teamName1 = _data["teamName1"];
            this.teamName2 = _data["teamName2"];
        }
    }

    static fromJS(data: any): HeadToHeadDto {
        data = typeof data === 'object' ? data : {};
        let result = new HeadToHeadDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["gameId"] = this.gameId;
        data["gameDate"] = this.gameDate ? this.gameDate.toISOString() : undefined as any;
        data["finalScore"] = this.finalScore;
        data["teamId1"] = this.teamId1;
        data["teamId2"] = this.teamId2;
        data["teamName1"] = this.teamName1;
        data["teamName2"] = this.teamName2;
        return data;
    }
}

export interface IHeadToHeadDto {
    gameId?: number;
    gameDate?: Date;
    finalScore: string;
    teamId1?: number;
    teamId2?: number;
    teamName1: string;
    teamName2: string;

    [key: string]: any;
}

export class LoginReq implements ILoginReq {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: ILoginReq) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginReq {
        data = typeof data === 'object' ? data : {};
        let result = new LoginReq();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginReq {
    email: string;
    password: string;

    [key: string]: any;
}

export class NewRoomDto implements INewRoomDto {
    name?: string;
    description?: string;
    tournamentId?: number;
    maxParticipants?: number;
    entryFee?: number | undefined;
    isPrivate?: boolean;

    [key: string]: any;

    constructor(data?: INewRoomDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.name = _data["name"];
            this.description = _data["description"];
            this.tournamentId = _data["tournamentId"];
            this.maxParticipants = _data["maxParticipants"];
            this.entryFee = _data["entryFee"];
            this.isPrivate = _data["isPrivate"];
        }
    }

    static fromJS(data: any): NewRoomDto {
        data = typeof data === 'object' ? data : {};
        let result = new NewRoomDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["name"] = this.name;
        data["description"] = this.description;
        data["tournamentId"] = this.tournamentId;
        data["maxParticipants"] = this.maxParticipants;
        data["entryFee"] = this.entryFee;
        data["isPrivate"] = this.isPrivate;
        return data;
    }
}

export interface INewRoomDto {
    name?: string;
    description?: string;
    tournamentId?: number;
    maxParticipants?: number;
    entryFee?: number | undefined;
    isPrivate?: boolean;

    [key: string]: any;
}

export class OtherGameBetSimpleDto implements IOtherGameBetSimpleDto {
    teamId?: number;
    win?: number;
    draw?: number;
    totalCount?: number;

    [key: string]: any;

    constructor(data?: IOtherGameBetSimpleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.teamId = _data["teamId"];
            this.win = _data["win"];
            this.draw = _data["draw"];
            this.totalCount = _data["totalCount"];
        }
    }

    static fromJS(data: any): OtherGameBetSimpleDto {
        data = typeof data === 'object' ? data : {};
        let result = new OtherGameBetSimpleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["teamId"] = this.teamId;
        data["win"] = this.win;
        data["draw"] = this.draw;
        data["totalCount"] = this.totalCount;
        return data;
    }
}

export interface IOtherGameBetSimpleDto {
    teamId?: number;
    win?: number;
    draw?: number;
    totalCount?: number;

    [key: string]: any;
}

export class PlayerBasicInfoDto implements IPlayerBasicInfoDto {
    id?: number;
    name?: string;
    position?: string;
    imageUrl?: string;
    shirtNumber?: number | undefined;

    [key: string]: any;

    constructor(data?: IPlayerBasicInfoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.position = _data["position"];
            this.imageUrl = _data["imageUrl"];
            this.shirtNumber = _data["shirtNumber"];
        }
    }

    static fromJS(data: any): PlayerBasicInfoDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerBasicInfoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["position"] = this.position;
        data["imageUrl"] = this.imageUrl;
        data["shirtNumber"] = this.shirtNumber;
        return data;
    }
}

export interface IPlayerBasicInfoDto {
    id?: number;
    name?: string;
    position?: string;
    imageUrl?: string;
    shirtNumber?: number | undefined;

    [key: string]: any;
}

export class RegistrationReq implements IRegistrationReq {
    username!: string;
    email!: string;
    lang!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: IRegistrationReq) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
            this.email = _data["email"];
            this.lang = _data["lang"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): RegistrationReq {
        data = typeof data === 'object' ? data : {};
        let result = new RegistrationReq();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        data["email"] = this.email;
        data["lang"] = this.lang;
        data["password"] = this.password;
        return data;
    }
}

export interface IRegistrationReq {
    username: string;
    email: string;
    lang: string;
    password: string;

    [key: string]: any;
}

export class RoomDTO implements IRoomDTO {
    id?: number;
    name?: string;
    description?: string;
    entryFee?: number | undefined;
    users?: RoomUserDTO[];
    maxUsers?: number | undefined;
    isPublic?: boolean;
    roomStatus?: number;
    tournamentId?: number;
    tournamentName?: string;
    tournamentLeague?: string;
    tournamentStartDate?: Date;
    tournamentEndDate?: Date;
    createdAt?: Date;
    createdByUserId?: number;
    isUserInRoom?: boolean;

    [key: string]: any;

    constructor(data?: IRoomDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.entryFee = _data["entryFee"];
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(RoomUserDTO.fromJS(item));
            }
            this.maxUsers = _data["maxUsers"];
            this.isPublic = _data["isPublic"];
            this.roomStatus = _data["roomStatus"];
            this.tournamentId = _data["tournamentId"];
            this.tournamentName = _data["tournamentName"];
            this.tournamentLeague = _data["tournamentLeague"];
            this.tournamentStartDate = _data["tournamentStartDate"] ? new Date(_data["tournamentStartDate"].toString()) : undefined as any;
            this.tournamentEndDate = _data["tournamentEndDate"] ? new Date(_data["tournamentEndDate"].toString()) : undefined as any;
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.createdByUserId = _data["createdByUserId"];
            this.isUserInRoom = _data["isUserInRoom"];
        }
    }

    static fromJS(data: any): RoomDTO {
        data = typeof data === 'object' ? data : {};
        let result = new RoomDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["entryFee"] = this.entryFee;
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item ? item.toJSON() : undefined as any);
        }
        data["maxUsers"] = this.maxUsers;
        data["isPublic"] = this.isPublic;
        data["roomStatus"] = this.roomStatus;
        data["tournamentId"] = this.tournamentId;
        data["tournamentName"] = this.tournamentName;
        data["tournamentLeague"] = this.tournamentLeague;
        data["tournamentStartDate"] = this.tournamentStartDate ? this.tournamentStartDate.toISOString() : undefined as any;
        data["tournamentEndDate"] = this.tournamentEndDate ? this.tournamentEndDate.toISOString() : undefined as any;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["createdByUserId"] = this.createdByUserId;
        data["isUserInRoom"] = this.isUserInRoom;
        return data;
    }
}

export interface IRoomDTO {
    id?: number;
    name?: string;
    description?: string;
    entryFee?: number | undefined;
    users?: RoomUserDTO[];
    maxUsers?: number | undefined;
    isPublic?: boolean;
    roomStatus?: number;
    tournamentId?: number;
    tournamentName?: string;
    tournamentLeague?: string;
    tournamentStartDate?: Date;
    tournamentEndDate?: Date;
    createdAt?: Date;
    createdByUserId?: number;
    isUserInRoom?: boolean;

    [key: string]: any;
}

export class RoomGameBetDto implements IRoomGameBetDto {
    gameId?: number;
    roomId?: number;
    roomGameBetTeam!: RoomGameBetTeamDto[];

    [key: string]: any;

    constructor(data?: IRoomGameBetDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.roomGameBetTeam = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.gameId = _data["gameId"];
            this.roomId = _data["roomId"];
            if (Array.isArray(_data["roomGameBetTeam"])) {
                this.roomGameBetTeam = [] as any;
                for (let item of _data["roomGameBetTeam"])
                    this.roomGameBetTeam!.push(RoomGameBetTeamDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RoomGameBetDto {
        data = typeof data === 'object' ? data : {};
        let result = new RoomGameBetDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["gameId"] = this.gameId;
        data["roomId"] = this.roomId;
        if (Array.isArray(this.roomGameBetTeam)) {
            data["roomGameBetTeam"] = [];
            for (let item of this.roomGameBetTeam)
                data["roomGameBetTeam"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IRoomGameBetDto {
    gameId?: number;
    roomId?: number;
    roomGameBetTeam: RoomGameBetTeamDto[];

    [key: string]: any;
}

export class RoomGameBetTeamDto implements IRoomGameBetTeamDto {
    teamId?: number;
    bet!: string;

    [key: string]: any;

    constructor(data?: IRoomGameBetTeamDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.teamId = _data["teamId"];
            this.bet = _data["bet"];
        }
    }

    static fromJS(data: any): RoomGameBetTeamDto {
        data = typeof data === 'object' ? data : {};
        let result = new RoomGameBetTeamDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["teamId"] = this.teamId;
        data["bet"] = this.bet;
        return data;
    }
}

export interface IRoomGameBetTeamDto {
    teamId?: number;
    bet: string;

    [key: string]: any;
}

export class RoomGameDto implements IRoomGameDto {
    gameId?: number;
    teams!: TeamUserBetDto[];
    roomId?: number;

    [key: string]: any;

    constructor(data?: IRoomGameDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.teams = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.gameId = _data["gameId"];
            if (Array.isArray(_data["teams"])) {
                this.teams = [] as any;
                for (let item of _data["teams"])
                    this.teams!.push(TeamUserBetDto.fromJS(item));
            }
            this.roomId = _data["roomId"];
        }
    }

    static fromJS(data: any): RoomGameDto {
        data = typeof data === 'object' ? data : {};
        let result = new RoomGameDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["gameId"] = this.gameId;
        if (Array.isArray(this.teams)) {
            data["teams"] = [];
            for (let item of this.teams)
                data["teams"].push(item ? item.toJSON() : undefined as any);
        }
        data["roomId"] = this.roomId;
        return data;
    }
}

export interface IRoomGameDto {
    gameId?: number;
    teams: TeamUserBetDto[];
    roomId?: number;

    [key: string]: any;
}

export class RoomUserDTO implements IRoomUserDTO {
    id?: number;
    userRoomRole?: UserRoomRole;

    [key: string]: any;

    constructor(data?: IRoomUserDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.userRoomRole = _data["userRoomRole"];
        }
    }

    static fromJS(data: any): RoomUserDTO {
        data = typeof data === 'object' ? data : {};
        let result = new RoomUserDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["userRoomRole"] = this.userRoomRole;
        return data;
    }
}

export interface IRoomUserDTO {
    id?: number;
    userRoomRole?: UserRoomRole;

    [key: string]: any;
}

export class TeamUserBetDto implements ITeamUserBetDto {
    bet?: string | undefined;
    id?: number;
    name?: string;
    slug?: string;
    imageUrl?: string;

    [key: string]: any;

    constructor(data?: ITeamUserBetDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.bet = _data["bet"];
            this.id = _data["id"];
            this.name = _data["name"];
            this.slug = _data["slug"];
            this.imageUrl = _data["imageUrl"];
        }
    }

    static fromJS(data: any): TeamUserBetDto {
        data = typeof data === 'object' ? data : {};
        let result = new TeamUserBetDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["bet"] = this.bet;
        data["id"] = this.id;
        data["name"] = this.name;
        data["slug"] = this.slug;
        data["imageUrl"] = this.imageUrl;
        return data;
    }
}

export interface ITeamUserBetDto {
    bet?: string | undefined;
    id?: number;
    name?: string;
    slug?: string;
    imageUrl?: string;

    [key: string]: any;
}

export class TournamentDto implements ITournamentDto {
    id?: number;
    sportCategoryId?: number;
    name?: string;
    description?: string | undefined;
    league?: string | undefined;
    matchesCount?: number;
    startDate?: Date;
    endDate?: Date;
    logoUrl?: string | undefined;

    [key: string]: any;

    constructor(data?: ITournamentDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.sportCategoryId = _data["sportCategoryId"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.league = _data["league"];
            this.matchesCount = _data["matchesCount"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : undefined as any;
            this.logoUrl = _data["logoUrl"];
        }
    }

    static fromJS(data: any): TournamentDto {
        data = typeof data === 'object' ? data : {};
        let result = new TournamentDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["sportCategoryId"] = this.sportCategoryId;
        data["name"] = this.name;
        data["description"] = this.description;
        data["league"] = this.league;
        data["matchesCount"] = this.matchesCount;
        data["startDate"] = this.startDate ? this.startDate.toISOString() : undefined as any;
        data["endDate"] = this.endDate ? this.endDate.toISOString() : undefined as any;
        data["logoUrl"] = this.logoUrl;
        return data;
    }
}

export interface ITournamentDto {
    id?: number;
    sportCategoryId?: number;
    name?: string;
    description?: string | undefined;
    league?: string | undefined;
    matchesCount?: number;
    startDate?: Date;
    endDate?: Date;
    logoUrl?: string | undefined;

    [key: string]: any;
}

export class UserDto implements IUserDto {
    id?: number;
    email?: string;
    name?: string;

    [key: string]: any;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.email = _data["email"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["email"] = this.email;
        data["name"] = this.name;
        return data;
    }
}

export interface IUserDto {
    id?: number;
    email?: string;
    name?: string;

    [key: string]: any;
}

export enum UserRoomRole {
    Participant = "Participant",
    Admin = "Admin",
    Moderator = "Moderator",
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}