export const COUNTRY_FLAG_MAP: Record<string, string> = {
  Albania: "AL",
  Andorra: "AD",
  Armenia: "AM",
  Austria: "AT",
  Azerbaijan: "AZ",
  Belarus: "BY",
  Belgium: "BE",
  "Bosnia & Herzegovina": "BA",
  Bulgaria: "BG",
  Croatia: "HR",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  England: "GB-ENG",
  Estonia: "EE",
  "Faroe Islands": "FO",
  Finland: "FI",
  France: "FR",
  "FYR Macedonia": "MK",
  Georgia: "GE",
  Germany: "DE",
  Gibraltar: "GI",
  Greece: "GR",
  Hungary: "HU",
  Iceland: "IS",
  Israel: "IL",
  Italy: "IT",
  Kazakhstan: "KZ",
  Kosovo: "XK",
  Latvia: "LV",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Malta: "MT",
  Moldova: "MD",
  Montenegro: "ME",
  Netherlands: "NL",
  "Northern Ireland": "GB-NIR",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  "Rep. Of Ireland": "IE",
  Romania: "RO",
  Russia: "RU",
  "San Marino": "SM",
  Scotland: "GB-SCT",
  Serbia: "RS",
  Slovakia: "SK",
  Slovenia: "SI",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Türkiye: "TR",
  Ukraine: "UA",
  Wales: "GB-WLS",
};
